# Generated by Django 5.0.2 on 2024-02-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=100, null=True)),
                ('Mobile', models.CharField(max_length=10, null=True)),
                ('Password', models.CharField(max_length=16, null=True)),
                ('OTP', models.CharField(max_length=6, null=True)),
                ('Token', models.CharField(max_length=200, null=True)),
                ('Active', models.BooleanField(default=False)),
            ],
        ),
    ]
