# Generated by Django 5.0.2 on 2024-02-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignUp',
            new_name='SignUpUser',
        ),
    ]
