# Generated by Django 5.0.2 on 2024-02-27 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_signup_signupuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('City_Name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('State_Name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Area_Name', models.CharField(max_length=100, null=True)),
                ('Pincode', models.CharField(max_length=6, null=True)),
                ('City_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.city')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=50, null=True)),
                ('Last_Name', models.CharField(max_length=50, null=True)),
                ('DOB', models.DateField(null=True)),
                ('Address', models.TextField(max_length=500, null=True)),
                ('Area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.area')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='State_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.state'),
        ),
    ]
