# Generated by Django 5.0.2 on 2024-02-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_city_state_area_customer_profile_city_state_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_profile',
            old_name='Area',
            new_name='Area_Name',
        ),
    ]
