# Generated by Django 5.0.2 on 2024-02-27 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_customer_profile_dp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('Category_Name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer_profile',
            name='dp',
            field=models.ImageField(null=True, upload_to='myapp/media'),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('Subcategory_Name', models.CharField(max_length=100, null=True)),
                ('c_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
    ]
