# Generated by Django 5.0.2 on 2024-02-28 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_Items',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('P_name', models.CharField(max_length=100, null=True)),
                ('P_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('c_QTY', models.IntegerField(default=1)),
                ('c_Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('c_DateTime', models.DateTimeField(auto_now=True)),
                ('c_Status', models.CharField(choices=[('pending', 'PENDING'), ('inorder', 'INORDER')], max_length=20)),
                ('lid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.signupuser')),
                ('p_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Details',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
                ('Address', models.TextField(max_length=500, null=True)),
                ('o_Status', models.CharField(choices=[('pending', 'PENDING'), ('placed', 'PLACED'), ('cancled', 'CANCLED')], max_length=20)),
                ('o_DateTime', models.DateTimeField(auto_now=True)),
                ('Grand_Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.area')),
                ('Cart_Items', models.ManyToManyField(to='myapp.cart_items')),
                ('lid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.signupuser')),
            ],
        ),
    ]
