# Generated by Django 5.0.2 on 2024-02-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_stock_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Category_Image',
            field=models.ImageField(null=True, upload_to='myapp/media'),
        ),
    ]
