# Generated by Django 5.0.2 on 2024-02-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='SubCategory_Image',
            field=models.ImageField(null=True, upload_to='myapp/media'),
        ),
    ]
