# Generated by Django 5.0.2 on 2024-03-07 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_shipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlit',
            fields=[
                ('W_id', models.AutoField(primary_key=True, serialize=False)),
                ('lid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.signupuser')),
                ('p_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
    ]
