# Generated by Django 5.0.2 on 2024-03-07 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_wishlit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlit',
            new_name='Wishlist',
        ),
    ]
