# Generated by Django 5.0.2 on 2024-03-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_shippingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_Details',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('Card_Number', models.IntegerField(null=True)),
                ('Card_Name', models.CharField(max_length=100, null=True)),
                ('Cvv_Code', models.IntegerField(null=True)),
                ('Expire_Date', models.IntegerField(null=True)),
            ],
        ),
    ]
