# Generated by Django 5.0.2 on 2024-03-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_card_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_details',
            name='Balance',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
