# Generated by Django 5.0.2 on 2024-03-12 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_order_details_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='Area',
        ),
        migrations.AddField(
            model_name='order_details',
            name='shipadd_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.shippingaddress'),
        ),
    ]
