# Generated by Django 5.0.2 on 2024-03-18 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_order_details_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_Signup',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('Mobile', models.CharField(max_length=10, null=True)),
                ('Email', models.EmailField(max_length=100, null=True)),
                ('Password', models.CharField(max_length=16, null=True)),
                ('OTP', models.CharField(max_length=6, null=True)),
                ('Token', models.CharField(max_length=200, null=True)),
                ('Active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='order_details',
            name='o_Status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('placed', 'PLACED'), ('cancled', 'CANCLED'), ('inreplace', 'INREPLACE')], max_length=20),
        ),
        migrations.CreateModel(
            name='Deliery_Profile',
            fields=[
                ('dp_id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=50, null=True)),
                ('Last_Name', models.CharField(max_length=50, null=True)),
                ('DOB', models.DateField(null=True)),
                ('Address', models.TextField(max_length=500, null=True)),
                ('dp', models.ImageField(null=True, upload_to='myapp/media')),
                ('Area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.area')),
                ('d_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.delivery_signup')),
            ],
        ),
    ]
