# Generated by Django 5.0.2 on 2024-03-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_delivery_signup_alter_order_details_o_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='o_Status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('placed', 'PLACED'), ('cancled', 'CANCLED'), ('inreplace', 'INREPLACE'), ('replaced', 'REPLACED')], max_length=20),
        ),
    ]
