# Generated by Django 5.0.2 on 2024-03-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_order_details_o_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('Coupan_Code', models.CharField(max_length=10, null=True)),
                ('Discount', models.IntegerField()),
                ('offer_Image', models.ImageField(null=True, upload_to='myapp/media')),
            ],
        ),
    ]
