# Generated by Django 5.0.2 on 2024-03-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_offers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offers',
        ),
    ]
