from django.urls import path
from myapp import views

urlpatterns = [
    path('',views.index, name='index'),
    path('subcategories/<int:c_id>/',views.subcategories,name='subcategories'),
    path('header/',views.header,name='header'),
    path('otp/',views.otp,name='otp'),
    path('cart/', views.cart,name='cart'),
    path('checkout/', views.checkout,name='checkout'),
    path('contact/', views.contact,name='contact'),
    path('detail/<int:p_id>/', views.detail,name='detail'),
    path('Shop/', views.Shop, name='Shop'),
    path('shop/<int:s_id>/', views.shop, name='shop'),
    path('login/', views.login,name='login'),
    path('forgetpass/', views.forgetpass,name='forgetpass'),
    path('SignUp', views.SignUp,name='SignUp'),
    path('userlogin', views.userlogin,name='userlogin'),
    path('verifyuser_login', views.verifyuser_login,name='verifyuser_login'),
    path('resendOTP', views.resendOTP),
    path('userlogout', views.userlogout,name='userlogout'),
    path('CustomerProfile', views.CustomerProfile),
    path('add_to_cart', views.add_to_cart,name='add_to_cart'),
    path('sentMessage', views.sentMessage),
    path('profile/',views.profile,name='profile'),
    path('remove_cart',views.remove_cart,name='remove_cart'),
    path('cartupdate',views.cartupdate,name='cartupdate'),
    path('forgetpassword',views.forgetpassword,name='forgetpassword'),
    path('forgetotp/',views.forgetotp,name='forgetotp'),
    path('verifyforgetotp',views.verifyforgetotp,name='verifyforgetotp'),
    path('resetpass/',views.resetpass,name='resetpass'),
    path('resetpassword',views.resetpassword,name='resetpassword'),
    path('toggle_wishlist',views.toggle_wishlist,name='toggle_wishlist'),
    path('wishlist/',views.wishlist,name="wishlist"),
    path('Complete_Order',views.Complete_Order,name='Complete_Order'),
    path('orders/',views.orders,name="orders"),
    path('shippingaddress',views.shippingaddress,name='shippingaddress'),
    path('deleteshippingaddress/<int:shipaddid>/',views.deleteshippingaddress,name='deleteshippingaddress'),
    path('editshipaddress',views.editshipaddress,name='editshipaddress'),
    path('get_shipping_charge',views.get_shipping_charge,name='get_shipping_charge'),
    path('update_cart_plus',views.update_cart_plus,name='update_cart_plus'),
    path('update_cart_minus',views.update_cart_minus,name='update_cart_minus'),
    path('Cancel_Order',views.Cancel_Order,name='Cancel_Order'),
    path('Cancel_Replace',views.Cancel_Replace,name='Cancel_Replace'),
    path('delivery_signup',views.delivery_signup,name='delivery_signup'),
    path('delivery_login',views.delivery_login,name='delivery_login'),
    path('delivery_verifyotp',views.delivery_verifyotp,name='delivery_verifyotp'),
    path('delivery_logout',views.delivery_logout,name='delivery_logout'),
    path('delivery_View_Orders',views.delivery_View_Orders,name='delivery_View_Orders'),
    path('Complate_Delivery',views.Complate_Delivery,name='Complate_Delivery'),
    path('delivery_View_replace_orders',views.delivery_View_replace_orders,name='delivery_View_replace_orders'),
    path('complete_replace_order',views.complete_replace_order,name='complete_replace_order'),
    path('edit_delivery_profile',views.edit_delivery_profile,name='edit_delivery_profile'),
]
